export interface CountryCodeEntry {
  name: string;
  flag: string;
  code: string;
  isoCode: string;
  minLength: number;
  maxLength: number;
}

export const COUNTRY_CODES: CountryCodeEntry[] = [
  { name: 'Afghanistan', flag: '🇦🇫', code: '+93', isoCode: 'AF', minLength: 9, maxLength: 9 },
  { name: 'Albania', flag: '🇦🇱', code: '+355', isoCode: 'AL', minLength: 9, maxLength: 9 },
  { name: 'Algeria', flag: '🇩🇿', code: '+213', isoCode: 'DZ', minLength: 9, maxLength: 9 },
  { name: 'Andorra', flag: '🇦🇩', code: '+376', isoCode: 'AD', minLength: 6, maxLength: 9 },
  { name: 'Angola', flag: '🇦🇴', code: '+244', isoCode: 'AO', minLength: 9, maxLength: 9 },
  { name: 'Argentina', flag: '🇦🇷', code: '+54', isoCode: 'AR', minLength: 10, maxLength: 11 },
  { name: 'Armenia', flag: '🇦🇲', code: '+374', isoCode: 'AM', minLength: 8, maxLength: 8 },
  { name: 'Australia', flag: '🇦🇺', code: '+61', isoCode: 'AU', minLength: 9, maxLength: 9 },
  { name: 'Austria', flag: '🇦🇹', code: '+43', isoCode: 'AT', minLength: 10, maxLength: 13 },
  { name: 'Azerbaijan', flag: '🇦🇿', code: '+994', isoCode: 'AZ', minLength: 9, maxLength: 9 },
  { name: 'Bahrain', flag: '🇧🇭', code: '+973', isoCode: 'BH', minLength: 8, maxLength: 8 },
  { name: 'Bangladesh', flag: '🇧🇩', code: '+880', isoCode: 'BD', minLength: 10, maxLength: 10 },
  { name: 'Belarus', flag: '🇧🇾', code: '+375', isoCode: 'BY', minLength: 9, maxLength: 10 },
  { name: 'Belgium', flag: '🇧🇪', code: '+32', isoCode: 'BE', minLength: 9, maxLength: 9 },
  { name: 'Belize', flag: '🇧🇿', code: '+501', isoCode: 'BZ', minLength: 7, maxLength: 7 },
  { name: 'Benin', flag: '🇧🇯', code: '+229', isoCode: 'BJ', minLength: 8, maxLength: 8 },
  { name: 'Bhutan', flag: '🇧🇹', code: '+975', isoCode: 'BT', minLength: 8, maxLength: 8 },
  { name: 'Bolivia', flag: '🇧🇴', code: '+591', isoCode: 'BO', minLength: 8, maxLength: 8 },
  { name: 'Bosnia and Herzegovina', flag: '🇧🇦', code: '+387', isoCode: 'BA', minLength: 8, maxLength: 8 },
  { name: 'Botswana', flag: '🇧🇼', code: '+267', isoCode: 'BW', minLength: 7, maxLength: 8 },
  { name: 'Brazil', flag: '🇧🇷', code: '+55', isoCode: 'BR', minLength: 10, maxLength: 11 },
  { name: 'Brunei', flag: '🇧🇳', code: '+673', isoCode: 'BN', minLength: 7, maxLength: 7 },
  { name: 'Bulgaria', flag: '🇧🇬', code: '+359', isoCode: 'BG', minLength: 9, maxLength: 9 },
  { name: 'Burkina Faso', flag: '🇧🇫', code: '+226', isoCode: 'BF', minLength: 8, maxLength: 8 },
  { name: 'Burundi', flag: '🇧🇮', code: '+257', isoCode: 'BI', minLength: 8, maxLength: 8 },
  { name: 'Cambodia', flag: '🇰🇭', code: '+855', isoCode: 'KH', minLength: 8, maxLength: 9 },
  { name: 'Cameroon', flag: '🇨🇲', code: '+237', isoCode: 'CM', minLength: 9, maxLength: 9 },
  { name: 'Canada', flag: '🇨🇦', code: '+1', isoCode: 'CA', minLength: 10, maxLength: 10 },
  { name: 'Chad', flag: '🇹🇩', code: '+235', isoCode: 'TD', minLength: 8, maxLength: 8 },
  { name: 'Chile', flag: '🇨🇱', code: '+56', isoCode: 'CL', minLength: 9, maxLength: 9 },
  { name: 'China', flag: '🇨🇳', code: '+86', isoCode: 'CN', minLength: 11, maxLength: 11 },
  { name: 'Colombia', flag: '🇨🇴', code: '+57', isoCode: 'CO', minLength: 10, maxLength: 10 },
  { name: 'Congo', flag: '🇨🇬', code: '+242', isoCode: 'CG', minLength: 9, maxLength: 9 },
  { name: 'Costa Rica', flag: '🇨🇷', code: '+506', isoCode: 'CR', minLength: 8, maxLength: 8 },
  { name: 'Croatia', flag: '🇭🇷', code: '+385', isoCode: 'HR', minLength: 8, maxLength: 9 },
  { name: 'Cuba', flag: '🇨🇺', code: '+53', isoCode: 'CU', minLength: 8, maxLength: 8 },
  { name: 'Cyprus', flag: '🇨🇾', code: '+357', isoCode: 'CY', minLength: 8, maxLength: 8 },
  { name: 'Czech Republic', flag: '🇨🇿', code: '+420', isoCode: 'CZ', minLength: 9, maxLength: 9 },
  { name: 'Denmark', flag: '🇩🇰', code: '+45', isoCode: 'DK', minLength: 8, maxLength: 8 },
  { name: 'Djibouti', flag: '🇩🇯', code: '+253', isoCode: 'DJ', minLength: 8, maxLength: 8 },
  { name: 'Dominican Republic', flag: '🇩🇴', code: '+1', isoCode: 'DO', minLength: 10, maxLength: 10 },
  { name: 'DR Congo', flag: '🇨🇩', code: '+243', isoCode: 'CD', minLength: 9, maxLength: 9 },
  { name: 'Ecuador', flag: '🇪🇨', code: '+593', isoCode: 'EC', minLength: 9, maxLength: 9 },
  { name: 'Egypt', flag: '🇪🇬', code: '+20', isoCode: 'EG', minLength: 10, maxLength: 10 },
  { name: 'El Salvador', flag: '🇸🇻', code: '+503', isoCode: 'SV', minLength: 8, maxLength: 8 },
  { name: 'Eritrea', flag: '🇪🇷', code: '+291', isoCode: 'ER', minLength: 7, maxLength: 7 },
  { name: 'Estonia', flag: '🇪🇪', code: '+372', isoCode: 'EE', minLength: 7, maxLength: 8 },
  { name: 'Eswatini', flag: '🇸🇿', code: '+268', isoCode: 'SZ', minLength: 8, maxLength: 8 },
  { name: 'Ethiopia', flag: '🇪🇹', code: '+251', isoCode: 'ET', minLength: 9, maxLength: 9 },
  { name: 'Fiji', flag: '🇫🇯', code: '+679', isoCode: 'FJ', minLength: 7, maxLength: 7 },
  { name: 'Finland', flag: '🇫🇮', code: '+358', isoCode: 'FI', minLength: 9, maxLength: 11 },
  { name: 'France', flag: '🇫🇷', code: '+33', isoCode: 'FR', minLength: 9, maxLength: 9 },
  { name: 'Gabon', flag: '🇬🇦', code: '+241', isoCode: 'GA', minLength: 7, maxLength: 8 },
  { name: 'Gambia', flag: '🇬🇲', code: '+220', isoCode: 'GM', minLength: 7, maxLength: 7 },
  { name: 'Georgia', flag: '🇬🇪', code: '+995', isoCode: 'GE', minLength: 9, maxLength: 9 },
  { name: 'Germany', flag: '🇩🇪', code: '+49', isoCode: 'DE', minLength: 10, maxLength: 12 },
  { name: 'Ghana', flag: '🇬🇭', code: '+233', isoCode: 'GH', minLength: 9, maxLength: 9 },
  { name: 'Greece', flag: '🇬🇷', code: '+30', isoCode: 'GR', minLength: 10, maxLength: 10 },
  { name: 'Guatemala', flag: '🇬🇹', code: '+502', isoCode: 'GT', minLength: 8, maxLength: 8 },
  { name: 'Guinea', flag: '🇬🇳', code: '+224', isoCode: 'GN', minLength: 9, maxLength: 9 },
  { name: 'Haiti', flag: '🇭🇹', code: '+509', isoCode: 'HT', minLength: 8, maxLength: 8 },
  { name: 'Honduras', flag: '🇭🇳', code: '+504', isoCode: 'HN', minLength: 8, maxLength: 8 },
  { name: 'Hong Kong', flag: '🇭🇰', code: '+852', isoCode: 'HK', minLength: 8, maxLength: 8 },
  { name: 'Hungary', flag: '🇭🇺', code: '+36', isoCode: 'HU', minLength: 9, maxLength: 9 },
  { name: 'Iceland', flag: '🇮🇸', code: '+354', isoCode: 'IS', minLength: 7, maxLength: 7 },
  { name: 'India', flag: '🇮🇳', code: '+91', isoCode: 'IN', minLength: 10, maxLength: 10 },
  { name: 'Indonesia', flag: '🇮🇩', code: '+62', isoCode: 'ID', minLength: 9, maxLength: 12 },
  { name: 'Iran', flag: '🇮🇷', code: '+98', isoCode: 'IR', minLength: 10, maxLength: 10 },
  { name: 'Iraq', flag: '🇮🇶', code: '+964', isoCode: 'IQ', minLength: 10, maxLength: 10 },
  { name: 'Ireland', flag: '🇮🇪', code: '+353', isoCode: 'IE', minLength: 9, maxLength: 9 },
  { name: 'Israel', flag: '🇮🇱', code: '+972', isoCode: 'IL', minLength: 9, maxLength: 9 },
  { name: 'Italy', flag: '🇮🇹', code: '+39', isoCode: 'IT', minLength: 9, maxLength: 11 },
  { name: 'Ivory Coast', flag: '🇨🇮', code: '+225', isoCode: 'CI', minLength: 8, maxLength: 8 },
  { name: 'Jamaica', flag: '🇯🇲', code: '+1', isoCode: 'JM', minLength: 10, maxLength: 10 },
  { name: 'Japan', flag: '🇯🇵', code: '+81', isoCode: 'JP', minLength: 10, maxLength: 11 },
  { name: 'Jordan', flag: '🇯🇴', code: '+962', isoCode: 'JO', minLength: 9, maxLength: 9 },
  { name: 'Kazakhstan', flag: '🇰🇿', code: '+7', isoCode: 'KZ', minLength: 10, maxLength: 10 },
  { name: 'Kenya', flag: '🇰🇪', code: '+254', isoCode: 'KE', minLength: 9, maxLength: 9 },
  { name: 'Kuwait', flag: '🇰🇼', code: '+965', isoCode: 'KW', minLength: 8, maxLength: 8 },
  { name: 'Kyrgyzstan', flag: '🇰🇬', code: '+996', isoCode: 'KG', minLength: 9, maxLength: 9 },
  { name: 'Laos', flag: '🇱🇦', code: '+856', isoCode: 'LA', minLength: 8, maxLength: 9 },
  { name: 'Latvia', flag: '🇱🇻', code: '+371', isoCode: 'LV', minLength: 8, maxLength: 8 },
  { name: 'Lebanon', flag: '🇱🇧', code: '+961', isoCode: 'LB', minLength: 7, maxLength: 8 },
  { name: 'Lesotho', flag: '🇱🇸', code: '+266', isoCode: 'LS', minLength: 8, maxLength: 8 },
  { name: 'Liberia', flag: '🇱🇷', code: '+231', isoCode: 'LR', minLength: 7, maxLength: 8 },
  { name: 'Libya', flag: '🇱🇾', code: '+218', isoCode: 'LY', minLength: 9, maxLength: 9 },
  { name: 'Liechtenstein', flag: '🇱🇮', code: '+423', isoCode: 'LI', minLength: 7, maxLength: 9 },
  { name: 'Lithuania', flag: '🇱🇹', code: '+370', isoCode: 'LT', minLength: 8, maxLength: 8 },
  { name: 'Luxembourg', flag: '🇱🇺', code: '+352', isoCode: 'LU', minLength: 9, maxLength: 11 },
  { name: 'Madagascar', flag: '🇲🇬', code: '+261', isoCode: 'MG', minLength: 9, maxLength: 9 },
  { name: 'Malawi', flag: '🇲🇼', code: '+265', isoCode: 'MW', minLength: 9, maxLength: 9 },
  { name: 'Malaysia', flag: '🇲🇾', code: '+60', isoCode: 'MY', minLength: 9, maxLength: 10 },
  { name: 'Maldives', flag: '🇲🇻', code: '+960', isoCode: 'MV', minLength: 7, maxLength: 7 },
  { name: 'Mali', flag: '🇲🇱', code: '+223', isoCode: 'ML', minLength: 8, maxLength: 8 },
  { name: 'Malta', flag: '🇲🇹', code: '+356', isoCode: 'MT', minLength: 8, maxLength: 8 },
  { name: 'Mauritania', flag: '🇲🇷', code: '+222', isoCode: 'MR', minLength: 8, maxLength: 8 },
  { name: 'Mauritius', flag: '🇲🇺', code: '+230', isoCode: 'MU', minLength: 8, maxLength: 8 },
  { name: 'Mexico', flag: '🇲🇽', code: '+52', isoCode: 'MX', minLength: 10, maxLength: 10 },
  { name: 'Moldova', flag: '🇲🇩', code: '+373', isoCode: 'MD', minLength: 8, maxLength: 8 },
  { name: 'Monaco', flag: '🇲🇨', code: '+377', isoCode: 'MC', minLength: 8, maxLength: 9 },
  { name: 'Mongolia', flag: '🇲🇳', code: '+976', isoCode: 'MN', minLength: 8, maxLength: 8 },
  { name: 'Montenegro', flag: '🇲🇪', code: '+382', isoCode: 'ME', minLength: 8, maxLength: 8 },
  { name: 'Morocco', flag: '🇲🇦', code: '+212', isoCode: 'MA', minLength: 9, maxLength: 9 },
  { name: 'Mozambique', flag: '🇲🇿', code: '+258', isoCode: 'MZ', minLength: 9, maxLength: 9 },
  { name: 'Myanmar', flag: '🇲🇲', code: '+95', isoCode: 'MM', minLength: 8, maxLength: 10 },
  { name: 'Namibia', flag: '🇳🇦', code: '+264', isoCode: 'NA', minLength: 9, maxLength: 9 },
  { name: 'Nepal', flag: '🇳🇵', code: '+977', isoCode: 'NP', minLength: 10, maxLength: 10 },
  { name: 'Netherlands', flag: '🇳🇱', code: '+31', isoCode: 'NL', minLength: 9, maxLength: 9 },
  { name: 'New Zealand', flag: '🇳🇿', code: '+64', isoCode: 'NZ', minLength: 8, maxLength: 10 },
  { name: 'Nicaragua', flag: '🇳🇮', code: '+505', isoCode: 'NI', minLength: 8, maxLength: 8 },
  { name: 'Niger', flag: '🇳🇪', code: '+227', isoCode: 'NE', minLength: 8, maxLength: 8 },
  { name: 'Nigeria', flag: '🇳🇬', code: '+234', isoCode: 'NG', minLength: 10, maxLength: 10 },
  { name: 'North Korea', flag: '🇰🇵', code: '+850', isoCode: 'KP', minLength: 9, maxLength: 10 },
  { name: 'North Macedonia', flag: '🇲🇰', code: '+389', isoCode: 'MK', minLength: 8, maxLength: 8 },
  { name: 'Norway', flag: '🇳🇴', code: '+47', isoCode: 'NO', minLength: 8, maxLength: 8 },
  { name: 'Oman', flag: '🇴🇲', code: '+968', isoCode: 'OM', minLength: 8, maxLength: 8 },
  { name: 'Pakistan', flag: '🇵🇰', code: '+92', isoCode: 'PK', minLength: 10, maxLength: 10 },
  { name: 'Palestine', flag: '🇵🇸', code: '+970', isoCode: 'PS', minLength: 9, maxLength: 9 },
  { name: 'Panama', flag: '🇵🇦', code: '+507', isoCode: 'PA', minLength: 8, maxLength: 8 },
  { name: 'Papua New Guinea', flag: '🇵🇬', code: '+675', isoCode: 'PG', minLength: 8, maxLength: 8 },
  { name: 'Paraguay', flag: '🇵🇾', code: '+595', isoCode: 'PY', minLength: 9, maxLength: 9 },
  { name: 'Peru', flag: '🇵🇪', code: '+51', isoCode: 'PE', minLength: 9, maxLength: 9 },
  { name: 'Philippines', flag: '🇵🇭', code: '+63', isoCode: 'PH', minLength: 10, maxLength: 10 },
  { name: 'Poland', flag: '🇵🇱', code: '+48', isoCode: 'PL', minLength: 9, maxLength: 9 },
  { name: 'Portugal', flag: '🇵🇹', code: '+351', isoCode: 'PT', minLength: 9, maxLength: 9 },
  { name: 'Qatar', flag: '🇶🇦', code: '+974', isoCode: 'QA', minLength: 8, maxLength: 8 },
  { name: 'Romania', flag: '🇷🇴', code: '+40', isoCode: 'RO', minLength: 9, maxLength: 9 },
  { name: 'Russia', flag: '🇷🇺', code: '+7', isoCode: 'RU', minLength: 10, maxLength: 10 },
  { name: 'Rwanda', flag: '🇷🇼', code: '+250', isoCode: 'RW', minLength: 9, maxLength: 9 },
  { name: 'Saudi Arabia', flag: '🇸🇦', code: '+966', isoCode: 'SA', minLength: 9, maxLength: 9 },
  { name: 'Senegal', flag: '🇸🇳', code: '+221', isoCode: 'SN', minLength: 9, maxLength: 9 },
  { name: 'Serbia', flag: '🇷🇸', code: '+381', isoCode: 'RS', minLength: 9, maxLength: 9 },
  { name: 'Sierra Leone', flag: '🇸🇱', code: '+232', isoCode: 'SL', minLength: 8, maxLength: 8 },
  { name: 'Singapore', flag: '🇸🇬', code: '+65', isoCode: 'SG', minLength: 8, maxLength: 8 },
  { name: 'Slovakia', flag: '🇸🇰', code: '+421', isoCode: 'SK', minLength: 9, maxLength: 9 },
  { name: 'Slovenia', flag: '🇸🇮', code: '+386', isoCode: 'SI', minLength: 8, maxLength: 8 },
  { name: 'Somalia', flag: '🇸🇴', code: '+252', isoCode: 'SO', minLength: 8, maxLength: 9 },
  { name: 'South Africa', flag: '🇿🇦', code: '+27', isoCode: 'ZA', minLength: 9, maxLength: 9 },
  { name: 'South Korea', flag: '🇰🇷', code: '+82', isoCode: 'KR', minLength: 9, maxLength: 10 },
  { name: 'South Sudan', flag: '🇸🇸', code: '+211', isoCode: 'SS', minLength: 9, maxLength: 9 },
  { name: 'Spain', flag: '🇪🇸', code: '+34', isoCode: 'ES', minLength: 9, maxLength: 9 },
  { name: 'Sri Lanka', flag: '🇱🇰', code: '+94', isoCode: 'LK', minLength: 9, maxLength: 9 },
  { name: 'Sudan', flag: '🇸🇩', code: '+249', isoCode: 'SD', minLength: 9, maxLength: 9 },
  { name: 'Sweden', flag: '🇸🇪', code: '+46', isoCode: 'SE', minLength: 9, maxLength: 9 },
  { name: 'Switzerland', flag: '🇨🇭', code: '+41', isoCode: 'CH', minLength: 9, maxLength: 9 },
  { name: 'Syria', flag: '🇸🇾', code: '+963', isoCode: 'SY', minLength: 9, maxLength: 9 },
  { name: 'Taiwan', flag: '🇹🇼', code: '+886', isoCode: 'TW', minLength: 9, maxLength: 9 },
  { name: 'Tajikistan', flag: '🇹🇯', code: '+992', isoCode: 'TJ', minLength: 9, maxLength: 9 },
  { name: 'Tanzania', flag: '🇹🇿', code: '+255', isoCode: 'TZ', minLength: 9, maxLength: 9 },
  { name: 'Thailand', flag: '🇹🇭', code: '+66', isoCode: 'TH', minLength: 9, maxLength: 9 },
  { name: 'Togo', flag: '🇹🇬', code: '+228', isoCode: 'TG', minLength: 8, maxLength: 8 },
  { name: 'Trinidad and Tobago', flag: '🇹🇹', code: '+1', isoCode: 'TT', minLength: 10, maxLength: 10 },
  { name: 'Tunisia', flag: '🇹🇳', code: '+216', isoCode: 'TN', minLength: 8, maxLength: 8 },
  { name: 'Turkey', flag: '🇹🇷', code: '+90', isoCode: 'TR', minLength: 10, maxLength: 10 },
  { name: 'Turkmenistan', flag: '🇹🇲', code: '+993', isoCode: 'TM', minLength: 8, maxLength: 8 },
  { name: 'Uganda', flag: '🇺🇬', code: '+256', isoCode: 'UG', minLength: 9, maxLength: 9 },
  { name: 'Ukraine', flag: '🇺🇦', code: '+380', isoCode: 'UA', minLength: 9, maxLength: 9 },
  { name: 'United Arab Emirates', flag: '🇦🇪', code: '+971', isoCode: 'AE', minLength: 9, maxLength: 9 },
  { name: 'United Kingdom', flag: '🇬🇧', code: '+44', isoCode: 'GB', minLength: 10, maxLength: 10 },
  { name: 'United States', flag: '🇺🇸', code: '+1', isoCode: 'US', minLength: 10, maxLength: 10 },
  { name: 'Uruguay', flag: '🇺🇾', code: '+598', isoCode: 'UY', minLength: 8, maxLength: 8 },
  { name: 'Uzbekistan', flag: '🇺🇿', code: '+998', isoCode: 'UZ', minLength: 9, maxLength: 9 },
  { name: 'Venezuela', flag: '🇻🇪', code: '+58', isoCode: 'VE', minLength: 10, maxLength: 10 },
  { name: 'Vietnam', flag: '🇻🇳', code: '+84', isoCode: 'VN', minLength: 9, maxLength: 10 },
  { name: 'Yemen', flag: '🇾🇪', code: '+967', isoCode: 'YE', minLength: 9, maxLength: 9 },
  { name: 'Zambia', flag: '🇿🇲', code: '+260', isoCode: 'ZM', minLength: 9, maxLength: 9 },
  { name: 'Zimbabwe', flag: '🇿🇼', code: '+263', isoCode: 'ZW', minLength: 9, maxLength: 9 },
];
